# Generated by Django 4.1.9 on 2023-06-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("systemSymbol", models.CharField(max_length=60)),
                ("symbol", models.CharField(max_length=60)),
                ("type", models.CharField(max_length=60)),
                ("coords_long", models.IntegerField(blank=True, null=True)),
                ("coords_lat", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("faction", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="WaypointTraits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trait",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="navigation.waypoint"
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="navigation.trait"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="waypoint",
            name="traits",
            field=models.ManyToManyField(through="navigation.WaypointTraits", to="navigation.trait"),
        ),
        migrations.AddField(
            model_name="trait",
            name="waypoints",
            field=models.ManyToManyField(through="navigation.WaypointTraits", to="navigation.waypoint"),
        ),
    ]
