# Generated by Django 4.1.9 on 2023-06-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cargo_name", models.CharField(max_length=60)),
                ("cargo_capacity", models.IntegerField(blank=True, null=True)),
                ("units_held", models.IntegerField(blank=True, null=True)),
                ("cargo_fill", models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ("full_cargo", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Cargo",
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ship_name", models.CharField(max_length=60)),
                ("faction", models.CharField(max_length=60)),
                ("role", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("departure_symbol", models.CharField(max_length=60)),
                ("departure_type", models.CharField(max_length=60)),
                ("departure_longitude", models.IntegerField(blank=True, null=True)),
                ("departure_latitude", models.IntegerField(blank=True, null=True)),
                ("destination_symbol", models.CharField(max_length=60)),
                ("destination_type", models.CharField(max_length=60)),
                ("destination_longitude", models.IntegerField(blank=True, null=True)),
                ("destination_latitude", models.IntegerField(blank=True, null=True)),
                ("fuel_current", models.IntegerField(blank=True, null=True)),
                ("fuel_capacity", models.IntegerField(blank=True, null=True)),
                ("fuel_consumed", models.IntegerField(blank=True, null=True)),
                ("fuel_percentage", models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ("flightmode", models.CharField(max_length=60)),
                ("ship_status", models.CharField(max_length=60)),
                ("location_current", models.CharField(max_length=60)),
                ("location_current_type", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="CargoLoad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=60)),
                ("units", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cargoload", to="ships.cargo"
                    ),
                ),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cargogoods", to="markets.good"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cargo",
            name="ship",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="ships.ship"),
        ),
    ]
