# Generated by Django 4.1.9 on 2023-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="departure",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="departure_symbol",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="departure_type",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="destination",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="destination_symbol",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="destination_type",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="faction",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="role",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="ship",
            name="ship_name",
            field=models.CharField(max_length=600),
        ),
    ]
