# Generated by Django 4.1.9 on 2023-05-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships", "0002_alter_ship_departure_alter_ship_departure_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="departure",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="departure_symbol",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="departure_type",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="destination",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="destination_symbol",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="destination_type",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="faction",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="role",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="ship",
            name="ship_name",
            field=models.CharField(max_length=60),
        ),
    ]
