# Generated by Django 4.1.9 on 2023-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships", "0004_remove_ship_departure_remove_ship_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="flightmode",
            field=models.CharField(default="pre-baptised", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ship",
            name="location_current",
            field=models.CharField(default="pre-baptised", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ship",
            name="location_current_type",
            field=models.CharField(default="pre-baptised", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ship",
            name="ship_status",
            field=models.CharField(default="pre-baptised", max_length=60),
            preserve_default=False,
        ),
    ]
