# Generated by Django 4.1.9 on 2023-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships", "0006_cargo_cargoload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargo",
            options={"verbose_name_plural": "Cargo"},
        ),
        migrations.AddField(
            model_name="cargoload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
