# Generated by Django 4.1.9 on 2023-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships", "0007_alter_cargo_options_cargoload_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
