# Generated by Django 4.1.9 on 2023-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships", "0008_cargoload_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
