# Generated by Django 4.1.9 on 2023-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ships", "0009_cargo_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="fuel_percentage",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
