# Generated by Django 4.1.9 on 2023-05-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Good",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=30)),
                ("tradeVolume", models.IntegerField(blank=True, null=True)),
                ("supply", models.IntegerField(blank=True, null=True)),
                ("purchasePrice", models.IntegerField(blank=True, null=True)),
                ("sellPrice", models.IntegerField(blank=True, null=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="goods", to="markets.market"
                    ),
                ),
            ],
        ),
    ]
