# Generated by Django 4.1.9 on 2023-05-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="supply",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
