# Generated by Django 4.1.9 on 2023-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="market_type",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
