# Generated by Django 4.1.9 on 2023-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0002_alter_good_supply"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="current",
            field=models.BooleanField(default=True),
        ),
    ]
