# Generated by Django 4.1.9 on 2023-05-25 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0003_market_current"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="current",
        ),
        migrations.AddField(
            model_name="market",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="market",
            name="symbol",
            field=models.CharField(max_length=60),
        ),
    ]
