# Generated by Django 4.1.9 on 2023-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0004_remove_market_current_market_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="type",
            field=models.CharField(default="pre-type", max_length=60),
            preserve_default=False,
        ),
    ]
