# Generated by Django 4.1.9 on 2023-05-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0005_market_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="good",
            name="market",
        ),
        migrations.CreateModel(
            name="MarketGoods",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("good", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="markets.good")),
                ("market", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="markets.market")),
            ],
        ),
        migrations.AddField(
            model_name="good",
            name="goods",
            field=models.ManyToManyField(through="markets.MarketGoods", to="markets.market"),
        ),
    ]
