# Generated by Django 4.1.9 on 2023-05-25 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0006_remove_good_market_marketgoods_good_goods"),
    ]

    operations = [
        migrations.RenameField(
            model_name="good",
            old_name="goods",
            new_name="markets",
        ),
    ]
