# Generated by Django 4.1.9 on 2023-05-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0007_rename_goods_good_markets"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketTrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("market", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="markets.market")),
            ],
        ),
        migrations.CreateModel(
            name="TradeGood",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=30)),
                ("tradeVolume", models.IntegerField(blank=True, null=True)),
                ("supply", models.CharField(blank=True, max_length=30, null=True)),
                ("purchasePrice", models.IntegerField(blank=True, null=True)),
                ("sellPrice", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="good",
            name="markets",
        ),
        migrations.RemoveField(
            model_name="good",
            name="purchasePrice",
        ),
        migrations.RemoveField(
            model_name="good",
            name="sellPrice",
        ),
        migrations.RemoveField(
            model_name="good",
            name="supply",
        ),
        migrations.RemoveField(
            model_name="good",
            name="tradeVolume",
        ),
        migrations.AddField(
            model_name="good",
            name="description",
            field=models.CharField(default="pre-correction", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="good",
            name="name",
            field=models.CharField(default="pre-correction", max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="MarketGoods",
        ),
        migrations.AddField(
            model_name="tradegood",
            name="good",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tradegoods", to="markets.good"
            ),
        ),
        migrations.AddField(
            model_name="tradegood",
            name="markets",
            field=models.ManyToManyField(through="markets.MarketTrade", to="markets.market"),
        ),
        migrations.AddField(
            model_name="markettrade",
            name="tradegood",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="markets.tradegood"),
        ),
    ]
