# Generated by Django 4.1.9 on 2023-05-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0009_alter_good_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradegood",
            name="markets",
        ),
        migrations.AddField(
            model_name="tradegood",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tradegoods",
                to="markets.market",
            ),
        ),
        migrations.DeleteModel(
            name="MarketTrade",
        ),
    ]
