# Generated by Django 4.1.9 on 2023-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0010_remove_tradegood_markets_tradegood_market_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradegood",
            name="tradegood_name",
            field=models.CharField(default="pre-Trex", max_length=30),
            preserve_default=False,
        ),
    ]
