# Generated by Django 4.1.9 on 2023-05-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0011_tradegood_tradegood_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradegood",
            name="tradegood_name",
            field=models.CharField(max_length=60),
        ),
    ]
