# Generated by Django 4.1.9 on 2023-06-07 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0012_alter_tradegood_tradegood_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="type",
        ),
    ]
