# Generated by Django 4.1.9 on 2023-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0013_remove_market_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradegood",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
