# Generated by Django 4.1.9 on 2023-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Extraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ship", models.CharField(max_length=60)),
                ("extracted", models.CharField(max_length=60)),
                ("units", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cooldown", models.IntegerField(blank=True, null=True)),
                ("cargo_capacity", models.IntegerField(blank=True, null=True)),
                ("units_held", models.IntegerField(blank=True, null=True)),
                ("full_cargo", models.BooleanField(default=False)),
            ],
        ),
    ]
