# Generated by Django 4.1.9 on 2023-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Extraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ship", models.CharField(max_length=60)),
                ("extracted", models.CharField(max_length=60)),
                ("units", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cooldown_from", models.DateTimeField(blank=True, null=True)),
                ("extraction_name", models.CharField(max_length=200)),
            ],
        ),
    ]
