# Generated by Django 4.1.9 on 2023-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraction",
            name="cargo_fill",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
