# Generated by Django 4.1.9 on 2023-05-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0003_extraction_extraction_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraction",
            name="cargo_fill",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
