# Generated by Django 4.1.9 on 2023-06-07 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0004_alter_extraction_cargo_fill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extraction",
            name="cargo_capacity",
        ),
        migrations.RemoveField(
            model_name="extraction",
            name="cargo_fill",
        ),
        migrations.RemoveField(
            model_name="extraction",
            name="full_cargo",
        ),
        migrations.RemoveField(
            model_name="extraction",
            name="units_held",
        ),
    ]
