# Generated by Django 4.1.9 on 2023-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractions", "0005_remove_extraction_cargo_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extraction",
            name="cooldown",
        ),
        migrations.AddField(
            model_name="extraction",
            name="cooldown_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
