# Generated by Django 4.1.9 on 2023-06-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=60)),
                ("accountId", models.CharField(max_length=60)),
                ("hq", models.CharField(max_length=60)),
                ("faction", models.CharField(max_length=60)),
                ("credits", models.IntegerField(blank=True, null=True)),
                ("agent_token", models.CharField(max_length=1000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agent", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
