# Generated by Django 4.1.9 on 2023-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(default="symbol_default", max_length=60)),
                ("accountId", models.CharField(default="accountId_default", max_length=60, null=True)),
                ("hq", models.CharField(default="hq_default", max_length=60)),
                ("faction", models.CharField(default="faction_default", max_length=60)),
                ("credits", models.IntegerField(blank=True, null=True)),
                ("agent_token", models.CharField(default="token_default", max_length=1000)),
            ],
        ),
    ]
