# Generated by Django 4.1.9 on 2023-06-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="current_ship",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
