# Generated by Django 4.1.9 on 2023-06-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agents", "0002_alter_agent_agent_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="agents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
